In [1]:
import torch
import numpy as np

In [2]:
# 데이터로부터 직접 생성
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
# Numpy 배열로부터 생성
np_array = np.array(data)
print(np_array)

x_np = torch.from_numpy(np_array) # np.ndarray -> tensor
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [6]:
# 다른 텐서로부터 생성
x_ones = torch.ones_like(x_np)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)


tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[0.2874, 0.5947],
        [0.1337, 0.3469]])


In [9]:
# 무작위, 상수 값 사용
shape = (2, 3,)
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(one_tensor)
print(zeros_tensor)

tensor([[0.9834, 0.5001, 0.0439],
        [0.0243, 0.8335, 0.8447]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# 텐서 속성: 모양, 자료형, 어느 장치
tensor = torch.rand(3, 4)

print('shape: ', tensor.shape)
print('type: ', tensor.dtype)
print('device: ', tensor.device)

shape:  torch.Size([3, 4])
type:  torch.float32
device:  cpu


In [11]:
# tensor를 cpu->gpu로 할당
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print('device: ', tensor.device)

device:  cuda:0


In [15]:
# tensor 연산
tensor = torch.ones(4, 4)
print(tensor)
print('first row:' , tensor[0])
print('first col:', tensor[:, 0])
print('last col:', tensor[..., -1])

tensor[:, 1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
first row: tensor([1., 1., 1., 1.])
first col: tensor([1., 1., 1., 1.])
last col: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
# tesor 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [22]:
# 산술 연산
# multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(y1)
print(y2)
print(y3)

# element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(z1)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [23]:
# tensor -> 숫자값
agg = tensor.sum()
agg_item = agg.item()

print(agg)
print(agg_item)


tensor(12.)
