In [16]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [19]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            
            nn.Linear(512, 512),
            nn.ReLU(),

            nn.Linear(512, 10)
        )
    
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [20]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [25]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)

print(pred_probab)
y_pred = pred_probab.argmax(dim=1)

print(y_pred)

tensor([[0.0989, 0.1181, 0.0978, 0.0896, 0.1022, 0.1011, 0.1029, 0.0979, 0.0931,
         0.0984]], device='cuda:0', grad_fn=<SoftmaxBackward0>)
tensor([1], device='cuda:0')


In [32]:
# layer
input_image = torch.rand(3, 28, 28)
print(input_image.size())

# nn.Flatten()
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

# nn.Linear()
layer1 = nn.Linear(28*28, 20)
hidden1 = layer1(flat_image)
print(hidden1.size()) # 출력 노드

# nn.ReLU()
print('before ReLU', hidden1)
hidden1 = nn.ReLU()(hidden1)
print('After ReLU', hidden1)

torch.Size([3, 28, 28])
torch.Size([3, 784])
torch.Size([3, 20])
before ReLU tensor([[-0.5910, -0.7167, -0.3618,  0.3209,  0.5378, -0.1044, -0.2542, -0.3182,
          0.3971, -0.1201,  0.0933, -0.0684,  0.0223,  0.0213,  0.1676, -0.2781,
          0.0162,  0.3423, -0.0207,  0.5020],
        [-0.4686, -0.2836, -0.3087,  0.0722,  0.6546, -0.1088,  0.0632, -0.0391,
          0.1100, -0.2157,  0.2325, -0.1165, -0.1078, -0.0205,  0.2766,  0.1024,
         -0.0531,  0.1491, -0.0570,  0.4572],
        [-0.6033, -0.8135, -0.2556,  0.4157,  0.4789, -0.0618,  0.1661, -0.3748,
          0.3502, -0.4711,  0.2854, -0.3415, -0.1537,  0.1621, -0.0407,  0.1447,
          0.1089,  0.3265, -0.3637,  0.4490]], grad_fn=<AddmmBackward0>)
After ReLU tensor([[0.0000, 0.0000, 0.0000, 0.3209, 0.5378, 0.0000, 0.0000, 0.0000, 0.3971,
         0.0000, 0.0933, 0.0000, 0.0223, 0.0213, 0.1676, 0.0000, 0.0162, 0.3423,
         0.0000, 0.5020],
        [0.0000, 0.0000, 0.0000, 0.0722, 0.6546, 0.0000, 0.0632, 0.0000, 

In [38]:
# nn.Sequential
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)

input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)

# nn.Softmax
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

print(pred_probab) # batch마다의 softmax output

tensor([[0.1026, 0.1004, 0.0829, 0.0969, 0.1165, 0.1103, 0.1036, 0.0935, 0.0867,
         0.1067],
        [0.1010, 0.1023, 0.0689, 0.0969, 0.1043, 0.1264, 0.1246, 0.0775, 0.0863,
         0.1118],
        [0.1145, 0.0923, 0.0655, 0.0942, 0.1180, 0.1141, 0.1192, 0.0880, 0.0870,
         0.1073]], grad_fn=<SoftmaxBackward0>)


In [ ]:
# 모델 매개변수
print(f'Model struture: {model}\n\n')

for name, param in model.named_parameters():
    print(f'Layer: {name} | size: {param.size()} | Values: {param[:2]}\n')